version: '3.1'

services:
  service:
    container_name: mutant-service
    build: .
    ports:
      - 8080:8080
    networks:
      - net
    depends_on:
      - db
    restart: always
  
  db:
    image: mongo:3.4
    container_name: mutant-mongo
    networks:
      - net
    volumes:
      - mongostore:/data/db
    restart: always
#    ports:  # for demo/debug purpose only
#      - 27018:27017
    
volumes:
  mongostore:
  
networks:
  net: